#!/bin/bash
# setup_termux.sh
# Host env gate — paths from TermuxHostPaths via fluxlinux-host.env (SSOT).
# Validates bundled host deps only; does not apt-install or rewrite ELFs.
#
# Marker records last successful validation version. Checks always re-run
# (marker never skips validation). Set FLUX_SETUP_FORCE=1 to clear marker first.

set -e
set -o pipefail

SETUP_VERSION="2"

# Bootstrap package identity until SSOT env file is sourced
PKG="${TERMUX_APP__PACKAGE_NAME:-com.ivarna.nativecode}"
PREFIX_DEFAULT="${TERMUX__PREFIX:-/data/data/${PKG}/files/usr}"
HOME_DEFAULT="${TERMUX__HOME:-/data/data/${PKG}/files/home}"

fail() {
    echo "FluxLinux: $*" >&2
    exit 1
}

trap 'ec=$?; echo "FluxLinux: Setup Failed! line=${LINENO} exit=${ec}" >&2; exit "${ec}"' ERR

# --- SSOT: generated by TermuxHostPaths.writeHostEnvFile ---
_HOST_ENV="${PREFIX_DEFAULT}/etc/fluxlinux-host.env"
if [ -r "$_HOST_ENV" ]; then
    # shellcheck source=/dev/null
    . "$_HOST_ENV"
fi

# Force package identity (env file + Kotlin ProcessBuilder must agree)
PKG="${TERMUX_APP__PACKAGE_NAME:-com.ivarna.nativecode}"
export TERMUX_APP__PACKAGE_NAME="$PKG"
export TERMUX_X11_OVERRIDE_PACKAGE="${TERMUX_X11_OVERRIDE_PACKAGE:-$PKG}"
export TERMUX__PREFIX="${TERMUX__PREFIX:-/data/data/${PKG}/files/usr}"
export TERMUX__HOME="${TERMUX__HOME:-/data/data/${PKG}/files/home}"
export PREFIX="$TERMUX__PREFIX"
export HOME="$TERMUX__HOME"
export TMPDIR="${TMPDIR:-$PREFIX/tmp}"
export PROOT_TMP_DIR="${PROOT_TMP_DIR:-$TMPDIR}"
export TERMUX_VERSION="${TERMUX_VERSION:-flux-host}"
export PATH="$PREFIX/bin:$PREFIX/bin/applets:/system/bin:/system/xbin${PATH:+:$PATH}"
export LD_LIBRARY_PATH="$PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

PREFIX_DEFAULT="$PREFIX"
HOME_DEFAULT="$HOME"

# Optional package-local profile (must already be rewritten off com.termux)
if [ -r "$PREFIX/etc/profile" ]; then
    # shellcheck source=/dev/null
    . "$PREFIX/etc/profile" || true
    # Re-pin after profile.d (may have leftover stock paths if rewrite missed)
    export TERMUX_APP__PACKAGE_NAME="$PKG"
    export TERMUX_X11_OVERRIDE_PACKAGE="$PKG"
    export TERMUX__PREFIX="$PREFIX_DEFAULT"
    export TERMUX__HOME="$HOME_DEFAULT"
    export PREFIX="$PREFIX_DEFAULT"
    export HOME="$HOME_DEFAULT"
    export TMPDIR="$PREFIX/tmp"
    export PROOT_TMP_DIR="$TMPDIR"
    export PATH="$PREFIX/bin:$PREFIX/bin/applets:/system/bin:/system/xbin${PATH:+:$PATH}"
    export LD_LIBRARY_PATH="$PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi

MARKER_DIR="$HOME/.fluxlinux"
MARKER_FILE="$MARKER_DIR/setup_termux.done"
mkdir -p "$MARKER_DIR" "$TMPDIR"

if [ "${FLUX_SETUP_FORCE:-0}" = "1" ]; then
    rm -f "$MARKER_FILE"
    echo "FluxLinux: FLUX_SETUP_FORCE=1 — cleared host setup marker"
fi

if [ -f "$MARKER_FILE" ]; then
    prev="$(cat "$MARKER_FILE" 2>/dev/null || true)"
    echo "FluxLinux: Prior marker v${prev:-?} — re-validating (checks never skipped)"
fi

echo "FluxLinux: Initializing host environment ($PKG)..."
echo "PREFIX=$PREFIX"
echo "HOME=$HOME"
echo "TERMUX_APP__PACKAGE_NAME=$TERMUX_APP__PACKAGE_NAME"
echo "SETUP_VERSION=$SETUP_VERSION"

# Refuse accidental com.termux prefix
case "$PREFIX" in
    *"/com.termux/"*)
        fail "PREFIX points at com.termux ($PREFIX); expected package $PKG"
        ;;
esac
[ -d "$PREFIX" ] || fail "Host prefix missing: $PREFIX"
[ -d "$PREFIX/bin" ] || fail "Host bin dir missing: $PREFIX/bin"

# --- Required host binaries on PATH under our prefix ---
required_bins=(proot-distro pulseaudio python)
for bin in "${required_bins[@]}"; do
    bin_path="$(command -v "$bin" 2>/dev/null || true)"
    if [ -z "$bin_path" ]; then
        fail "Missing bundled host dependency: $bin (expected under $PREFIX/bin, package $PKG)"
    fi
    case "$bin_path" in
        "$PREFIX"/*) ;;
        *)
            if [ -x "$PREFIX/bin/$bin" ]; then
                bin_path="$PREFIX/bin/$bin"
            else
                echo "FluxLinux: WARN $bin resolved outside prefix: $bin_path"
            fi
            ;;
    esac
    [ -x "$bin_path" ] || [ -f "$bin_path" ] || fail "Not executable/file: $bin_path"
    echo "FluxLinux: OK $bin -> $bin_path"
done

python -c "import sys; assert sys.version_info[0] >= 3" \
    || fail "python present but failed smoke import"

if [ -n "${PD_PROOT_BIN:-}" ] && [ -e "$PD_PROOT_BIN" ]; then
    echo "FluxLinux: OK PD_PROOT_BIN=$PD_PROOT_BIN"
elif [ -x "$PREFIX/bin/proot" ] || [ -f "$PREFIX/bin/proot" ]; then
    echo "FluxLinux: OK proot -> $PREFIX/bin/proot"
else
    fail "Missing proot (set PD_PROOT_BIN to libproot.so or install $PREFIX/bin/proot)"
fi

LOADER_APK="$PREFIX/libexec/termux-x11/loader.apk"
[ -f "$LOADER_APK" ] || fail "Missing Termux:X11 loader at $LOADER_APK"
[ -s "$LOADER_APK" ] || fail "Termux:X11 loader is empty: $LOADER_APK"
chmod 0400 "$LOADER_APK" 2>/dev/null || true
chmod 0500 "$PREFIX/libexec/termux-x11" 2>/dev/null || true
echo "FluxLinux: OK loader.apk ($(wc -c < "$LOADER_APK" | tr -d ' ') bytes)"

touch "$TMPDIR/.flux_setup_write_test" 2>/dev/null \
    || fail "TMPDIR not writable: $TMPDIR"
rm -f "$TMPDIR/.flux_setup_write_test"

printf '%s\n' "$SETUP_VERSION" > "$MARKER_FILE"
echo "FluxLinux: Setup Complete (marker v$SETUP_VERSION)"
echo ""
exit 0
