package com.ivarna.nativecode.terminal

import android.content.Context
import android.util.Log
import java.io.File

/**
 * Single source of truth for host (embedded Termux) package paths.
 *
 * Kotlin, generated `fluxlinux-host.env`, and bootstrap path rewrites all derive
 * from [PACKAGE]. Never hardcode `com.termux` defaults at call sites.
 */
object TermuxHostPaths {
    const val PACKAGE = "com.ivarna.nativecode"
    const val STOCK_PACKAGE = "com.termux"

    /** `/data/data/<package>` */
    const val DATA_ROOT = "/data/data/$PACKAGE"
    const val STOCK_DATA_ROOT = "/data/data/$STOCK_PACKAGE"

    const val FILES = "$DATA_ROOT/files"
    const val PREFIX = "$FILES/usr"
    const val HOME = "$FILES/home"
    const val TMPDIR = "$PREFIX/tmp"
    const val BIN = "$PREFIX/bin"
    const val LIB = "$PREFIX/lib"
    const val SSL_CERT = "$PREFIX/etc/tls/cert.pem"
    const val LOADER_APK = "$PREFIX/libexec/termux-x11/loader.apk"
    const val PROOT_DISTRO = "$BIN/proot-distro"
    const val TERMUX_VERSION = "flux-host"

    /** Relative path under app filesDir for generated shell env. */
    const val HOST_ENV_REL = "usr/etc/fluxlinux-host.env"

    private const val TAG = "TermuxHostPaths"
    private const val MAX_REWRITE_BYTES = 2_000_000L

    fun setupTermuxMarker(ctx: Context): File =
        File(ctx.filesDir, "home/.fluxlinux/setup_termux.done")

    fun clearSetupTermuxMarker(ctx: Context): Boolean =
        setupTermuxMarker(ctx).delete()

    fun libProot(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libproot.so")

    fun libLoader(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libloader.so")

    fun libBash(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libbash.so")

    fun termuxExec(ctx: Context): File =
        File(ctx.filesDir, "usr/lib/libtermux-exec.so")

    fun homeDir(ctx: Context): File =
        File(ctx.filesDir, "home")

    fun hostScript(ctx: Context, name: String): File =
        File(homeDir(ctx), name)

    fun hostEnvFile(filesDir: File): File =
        File(filesDir, HOST_ENV_REL)

    /** Replace stock Termux data-root paths with this package's paths. */
    fun rewriteStockPaths(text: String): String =
        text.replace(STOCK_DATA_ROOT, DATA_ROOT)

    /**
     * Write `usr/etc/fluxlinux-host.env` for shell scripts to source.
     * Generated from this object only — do not hand-edit on device.
     */
    fun writeHostEnvFile(filesDir: File): File {
        val f = hostEnvFile(filesDir)
        f.parentFile?.mkdirs()
        f.writeText(
            """
            |# Generated by TermuxHostPaths.kt — single source of truth. Do not edit.
            |export TERMUX_APP__PACKAGE_NAME="$PACKAGE"
            |export TERMUX_X11_OVERRIDE_PACKAGE="$PACKAGE"
            |export TERMUX__PREFIX="$PREFIX"
            |export TERMUX__HOME="$HOME"
            |export PREFIX="$PREFIX"
            |export HOME="$HOME"
            |export TMPDIR="$TMPDIR"
            |export PROOT_TMP_DIR="$TMPDIR"
            |export TERMUX_VERSION="$TERMUX_VERSION"
            |export SSL_CERT_FILE="$SSL_CERT"
            |export CURL_CA_BUNDLE="$SSL_CERT"
            |export PATH="$BIN:$BIN/applets:/system/bin:/system/xbin${'$'}{PATH:+:${'$'}PATH}"
            |export LD_LIBRARY_PATH="$LIB${'$'}{LD_LIBRARY_PATH:+:${'$'}LD_LIBRARY_PATH}"
            |""".trimMargin()
        )
        return f
    }

    /**
     * After bootstrap extract (and before host setup): rewrite residual
     * `/data/data/com.termux/...` text under the prefix, then write host env file.
     *
     * @return number of files rewritten
     */
    fun applyPackageToExtractedPrefix(filesDir: File): Int {
        var rewritten = 0
        val roots = listOf(
            File(filesDir, "usr/bin"),
            File(filesDir, "usr/etc"),
            File(filesDir, "usr/share"),
            File(filesDir, "usr/lib/python3.14/site-packages/proot_distro"),
            File(filesDir, "usr/include/termux-exec"),
        )
        for (root in roots) {
            if (!root.exists()) continue
            root.walkTopDown().forEach { file ->
                if (!file.isFile) return@forEach
                val len = file.length()
                if (len == 0L || len > MAX_REWRITE_BYTES) return@forEach
                try {
                    val bytes = file.readBytes()
                    // Skip binaries (NUL in first 512 bytes)
                    val scan = minOf(bytes.size, 512)
                    for (i in 0 until scan) {
                        if (bytes[i] == 0.toByte()) return@forEach
                    }
                    val text = bytes.toString(Charsets.UTF_8)
                    if (!text.contains(STOCK_DATA_ROOT)) return@forEach
                    file.writeText(rewriteStockPaths(text), Charsets.UTF_8)
                    rewritten++
                } catch (e: Exception) {
                    Log.w(TAG, "skip rewrite ${file.absolutePath}: ${e.message}")
                }
            }
        }
        writeHostEnvFile(filesDir)
        if (rewritten > 0) {
            Log.i(TAG, "rewrote $rewritten file(s): $STOCK_DATA_ROOT → $DATA_ROOT")
        }
        return rewritten
    }
}
